package com.example.demo;

import org.springframework.data.annotation.Id;

import java.util.Objects;

//TODO:Figure out what is req for this annotation
//@MappedSuperClass
public abstract class AbstractEntity {

    @Id
    //@GeneratedValue TODO: Search for dependency for this
    //TODO: Review adding autogenerated id
    private int id;

    public int getId() {
        return id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AbstractEntity that = (AbstractEntity) o;
        return id == that.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

}
