package com.example.demo;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
//import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

//import javax.persistence.Entity;
import javax.validation.constraints.NotNull;
import java.util.Objects;

//@Entity
public class User extends AbstractEntity {

    @Id
    //@GeneratedValue TODO: Search for dependency for this
    //TODO: Review adding autogenerated id
    private int id;

    //TODO: Review @Column annotations
    @NotNull
    //@Column (unique = true, length = 45)
    private String email;

    @NotNull
    //@Column (unique = true, length = 10)
    private String displayName;

    @NotNull
    //@Column (length = 64)
    private String password;

    @NotNull
    //@Column (name = "first_name")
    private String firstName;

    @NotNull
    //@Column (name = "last_name")
    private String lastName;

    //TODO: Research dependencies for import for this, then add to constructor
//    @NotNull
//    private String pwHash;
//
//    private static final BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();

    public User(int id, String email, String displayName, String password, String firstName, String lastName) {
        this.id = id;
        this.email = email;
        this.displayName = displayName;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public User (){
        //empty constructor
    }

    public int getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;
        User user = (User) o;
        return getId() == user.getId() && getEmail().equals(user.getEmail()) && getDisplayName().equals(user.getDisplayName()) && getPassword().equals(user.getPassword()) && getFirstName().equals(user.getFirstName()) && getLastName().equals(user.getLastName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getEmail(), getDisplayName(), getPassword(), getFirstName(), getLastName());
    }

    //TODO: Finish toString Method
//    @Override
//    public String toString() {
//        return User +
//                "email='" + email + '\'' +
//                ", displayName='" + displayName + '\'' +
//                ", password='" + password + '\'' +
//                ", firstName='" + firstName + '\'' +
//                ", lastName='" + lastName + '\'' +;
//    }

//    public boolean isMatchingPassword(String password) {
//        return encoder.matches(password, pwHash);
//    }
}
